"use strict";
const express = require("express");
const accountsStore = require("../ai-usage/store");
const projectStore = require("../postgres-store");
const store = require("./store");
const { buildState } = require("../state");
const { buildSystemPrompt } = require("./context");
const { pickProvider, selectAccount } = require("./provider");
const { streamMessage, isValidProjectId } = require("./stream");
const { validateProposedEvents } = require("./tools/propose-events");
const { assertRequirementTransition } = require("../state-machine");
const { httpError } = require("../errors");
const { createRateLimiter } = require("./rate-limit");

function user(req) { return req.user; }
function projectId(req) { return String(req.query.project || req.body?.projectId || "").trim(); }
async function requireProject(req, next) { const id=projectId(req); if(!isValidProjectId(id)){next(httpError(400,"INVALID_PROJECT","缺少或非法的 projectId"));return null;} const p=await projectStore.getProject(id,user(req).id); if(!p){next(httpError(404,"PROJECT_NOT_FOUND",`项目不存在：${id}`));return null;} return p; }
async function owned(root, project, conversationId, req) { const conv=await store.getConversation(root,project,conversationId); return conv&&conv.userId===user(req).id?conv:null; }
async function state(projectId) { return buildState(await projectStore.listEvents(projectId)); }
function transitions(current, events) { const statuses=new Map(current.items.map((item)=>[item.id,item.status])); for(const event of events){ if(event.status===undefined) continue; const from=statuses.get(event.requirementId); assertRequirementTransition(from,event.status,event.requirementId); statuses.set(event.requirementId,event.status); } }

function createAiRoutes(rootDir) {
  const router=express.Router(); const limiter=createRateLimiter({limit:30,windowMs:60_000});
  router.get("/providers",(_req,res)=>res.json({ok:true,providers:["deepseek"],default:"deepseek"}));
  router.get("/accounts",async (_req,res,next)=>{try{const accounts=await accountsStore.readAccounts();res.json({ok:true,accounts:accounts.filter((a)=>a.provider==="deepseek"&&a.enabled!==false).map((a)=>({id:a.id,accountName:a.accountName,baseUrl:a.baseUrl,modelId:a.modelId,hasApiKey:Boolean(a.apiKey)}))});}catch(error){next(error);}});
  router.post("/conversations",express.json(),async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const requirementId=String(req.body?.requirementId||"").trim()||null;if(requirementId&&!(await state(project.id)).items.some((item)=>item.id===requirementId))return next(httpError(404,"AI_REQUIREMENT_NOT_FOUND",`需求不存在：${requirementId}`));const conv=await store.createConversation(rootDir,project.id,{userId:user(req).id,requirementId,title:req.body?.title||null,model:req.body?.model||"deepseek-chat",accountId:req.body?.accountId||null});res.json({ok:true,conversation:conv});}catch(error){next(httpError(400,"AI_CONVERSATION_CREATE_FAILED",error.message));}});
  router.get("/conversations",async(req,res,next)=>{try{const project=await requireProject(req,next);if(project)res.json({ok:true,conversations:await store.listConversations(rootDir,project.id,{userId:user(req).id})});}catch(error){next(error);}});
  router.patch("/conversations/:id",express.json(),async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));const title=String(req.body?.title||"").trim();if(!title)return next(httpError(400,"AI_TITLE_EMPTY","标题不能为空"));const duplicate=await store.findDuplicateTitle(rootDir,project.id,title,req.params.id,user(req).id);if(duplicate)return next(httpError(409,"AI_TITLE_DUPLICATE",`已存在同名会话：${duplicate.title}`));await store.renameConversation(rootDir,project.id,conv.id,title);res.json({ok:true,conversation:await owned(rootDir,project.id,conv.id,req)});}catch(error){next(error);}});
  router.delete("/conversations/:id",async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));res.json({ok:true,...await store.deleteConversation(rootDir,project.id,conv.id)});}catch(error){next(error);}});
  router.get("/conversations/:id",async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));res.json({ok:true,conversation:conv,messages:await store.listMessages(rootDir,project.id,conv.id)});}catch(error){next(error);}});
  router.get("/conversations/:id/messages",async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));res.json({ok:true,conversationId:conv.id,messages:await store.listMessages(rootDir,project.id,conv.id)});}catch(error){next(error);}});
  router.post("/conversations/:id/messages/stream",limiter,express.json({limit:"1mb"}),async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));const text=String(req.body?.text||"").trim();if(!text)return next(httpError(400,"EMPTY_MESSAGE","消息内容为空"));require("./sse").setupSse(res);await streamMessage(rootDir,req,res,project.id,conv,{...req.body,text});}catch(error){if(!res.headersSent)next(error);else res.end();}});
  router.post("/conversations/:id/messages",limiter,express.json({limit:"1mb"}),async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));const text=String(req.body?.text||"").trim();if(!text)return next(httpError(400,"EMPTY_MESSAGE","消息内容为空"));const {mod:provider}=pickProvider(req.body?.provider||"deepseek");const account=selectAccount(await accountsStore.readAccounts(),{provider:req.body?.provider||"deepseek",accountId:req.body?.accountId||conv.accountId});const userMessage=await store.appendMessage(rootDir,project.id,{conversationId:conv.id,role:"user",content:text});if(!conv.title){const title=store.autoTitleFromText(text);if(title&&await store.setConversationTitleIfEmpty(rootDir,project.id,conv.id,title))conv.title=title;}const history=await store.listMessages(rootDir,project.id,conv.id);const result=await provider.chat([{role:"system",content:await buildSystemPrompt(rootDir,{projectId:project.id,requirementId:conv.requirementId})},...history.map((item)=>({role:item.role,content:item.content}))],{account,model:req.body?.model||conv.model});const assistantMessage=await store.appendMessage(rootDir,project.id,{conversationId:conv.id,role:"assistant",content:result.content,tokensIn:result.usage.inputTokens,tokensOut:result.usage.outputTokens});await store.touchConversation(rootDir,project.id,conv.id);res.json({ok:true,userMessage,assistantMessage,usage:result.usage,model:result.model});}catch(error){next(httpError(500,error.code||"AI_CHAT_FAILED",error.message));}});
  router.get("/conversations/:id/proposals",async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const conv=await owned(rootDir,project.id,req.params.id,req);if(!conv)return next(httpError(404,"AI_CONVERSATION_NOT_FOUND","会话不存在"));res.json({ok:true,proposals:await store.listProposals(rootDir,project.id,conv.id)});}catch(error){next(error);}});
  router.post("/proposals/:id/apply",express.json(),async(req,res,next)=>{try{const project=await requireProject(req,next);if(!project)return;const prop=await store.getProposal(rootDir,project.id,req.params.id);if(!prop)return next(httpError(404,"AI_PROPOSAL_NOT_FOUND","提案不存在"));const conv=await owned(rootDir,project.id,prop.conversationId,req);if(!conv)return next(httpError(404,"AI_PROPOSAL_NOT_FOUND","提案不存在"));if(prop.status!=="pending")return next(httpError(409,"AI_PROPOSAL_NOT_PENDING",`提案已是 ${prop.status} 状态`));const validation=validateProposedEvents(prop.events);if(!validation.valid)return next(httpError(400,"AI_PROPOSAL_INVALID","提案事件不符合写入范围",{errors:validation.errors}));const current=await state(project.id);transitions(current,validation.events);const ids=new Set(current.items.map((item)=>item.id));if(validation.events.some((event)=>!ids.has(event.requirementId)))return next(httpError(404,"AI_PROPOSAL_REQUIREMENT_NOT_FOUND","提案指向的需求不存在"));const events=validation.events.map((event)=>({...event,actor:event.actor||`ai:${user(req).id}`}));await projectStore.appendEvents(project.id,events);await store.markProposalApplied(rootDir,project.id,prop.id,user(req).id);res.json({ok:true,applied:events.length,proposalId:prop.id,items:(await state(project.id)).items.length});}catch(error){next(httpError(500,"AI_PROPOSAL_APPLY_FAILED",error.message));}});
  return router;
}
module.exports={createAiRoutes};
